#SpringBoot中Tomcat的服务端口
server:
  port: 8080
spring:
  application:
    name: reggie
#SpringBoot结合druid连接数据库
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
mybatis-plus:
  configuration:
    #在实体类或属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射.
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: assign_id
      
reggie:
  path: C:\Users\MI\IdeaProjects\Java\reggie\image\
